version: '3.6'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: supersecurepassword
      MYSQL_USER: docker
      MYSQL_PASSWORD: supersecurepassword
