version: '3.6'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: supersecurepassword
